name = "storybakery/bakery_vide_kit"
version = "0.1.0"
repository = "https://github.com/StoryBakery/BakeryVideKit"
includes = ["pesde.toml", "README.md", "src/**"]
private = true

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
vide = { name = "centau/vide", version = "^0.3.1-test.1" }
ui-labs = { wally = "pepeeltoro41/ui-labs", version = "^2.4.2" }
Maid = { repo = "https://github.com/StoryBakery/Maid", rev = "0fc3dddb5b709f30c90cf0d63f031113c26ce207" }
TableUtil = { repo = "https://github.com/StoryBakery/TableUtil", rev = "961700292dd382b062955e16cac7ccccc361cdfa" }
MathUtil = { repo = "https://github.com/StoryBakery/MathUtil", rev = "1d494fd68f7dbbe31d69aea05395d965623b6167" }
DynamicTimer = { repo = "https://github.com/StoryBakery/DynamicTimer", rev = "7abb2a1b7faba9b5f6e8d1ad031fab29182ebced" }
DynamicTween = { repo = "https://github.com/StoryBakery/DynamicTween", rev = "ee4f2e5dfb894f5d459a1dc573e2a0387020ad74" }
LinearInterpolation = { repo = "https://github.com/StoryBakery/LinearInterpolation", rev = "c522819b5515edb45f1518244252f58c8f9e05ee" }
UserInputManager = { repo = "https://github.com/StoryBakery/UserInputManager", rev = "f932f212b55f985c3126fb9804f07e604ca05470" }
ExtendedTranslator = { repo = "https://github.com/StoryBakery/ExtendedTranslator", rev = "18d4b7a7c10950235d0d196eb3ad605b65208216" }

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.5.1", target = "lune" }
setup-project-configs = { repo = "https://github.com/StoryBakery/setup-project-configs", rev = "8e77c9722c25b0a4ea6ed1415ab18fc8db2ff9e2" }
pesde-gitrev = { repo = "https://github.com/StoryBakery/pesde-gitrev", rev = "a2d6f1e71ac6264ff2b48fd2178271f80135772e" }

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"



